--Looking at each table
SELECT *
FROM [dbo].[artist$];

SELECT *
FROM [dbo].[canvas_size$];

SELECT *
FROM [dbo].[museum$];

SELECT *
FROM [dbo].[museum_hours$];

SELECT *
FROM [dbo].[product_size$];

SELECT *
FROM [dbo].[subject$];

SELECT *
FROM [dbo].[work$];



--adding the amount of dollars added to the sale price to a column named price_markup
ALTER TABLE dbo.[product_size$]
ADD price_markup float;

UPDATE dbo.[product_size$]
SET price_markup = regular_price - sale_price;


--Return the painting with the highest price markup
SELECT TOP 1
	work_id,
	price_markup
FROM dbo.product_size$
ORDER BY 2 DESC


--Looking at the amount of art pieces that come out of each country
SELECT 
	COUNT(work_id) as works_per_country,
	a.nationality
FROM work$ w
INNER JOIN artist$ a
ON w.artist_id = a.artist_id
GROUP BY a.nationality
ORDER BY 1 DESC;


--Comparing regular price to sale price.
SELECT 
	work_id,
	sale_price,
	regular_price,
	RANK() OVER(ORDER BY sale_price DESC) as sale_price_rank,
	RANK() OVER(ORDER BY regular_price DESC) as reg_price_sale
FROM dbo.product_size$;


--Which artist has made the most wealth from art sales 
SELECT 
	a.artist_id, 
	a.full_name,
	SUM(ps.regular_price) as total_sales
FROM dbo.work$ w
INNER JOIN dbo.product_size$ ps
ON w.work_id = ps.work_id
INNER JOIN dbo.artist$ a
ON w.artist_id = a.artist_id
GROUP BY a.artist_id, a.full_name
ORDER BY 3 DESC


--Which artist makes the most wealth per piece of art
SELECT 
	a.artist_id, 
	a.full_name,
	AVG(ps.regular_price) as avg_sales
FROM dbo.work$ w
INNER JOIN dbo.product_size$ ps
ON w.work_id = ps.work_id
INNER JOIN dbo.artist$ a
ON w.artist_id = a.artist_id
GROUP BY a.artist_id, a.full_name
ORDER BY 3 DESC


--Looking at the total amount of wealth, average amount of wealth, and amount of art pieces generated by art subject(EX: still life, landscape, etc.)
SELECT 
	s.[subject],
	SUM(ps.regular_price) as wealth_per_subject,
	COUNT(ps.regular_price) as art_pieces_per_subject,
	AVG (ps.regular_price) as avg_wealth_per_subject
FROM dbo.product_size$ ps
JOIN dbo.subject$ s
ON ps.work_id = s.work_id
GROUP BY [subject]
ORDER BY 2 DESC;


--What is the most expensive and least expensive piece of art 
WITH most_expensive AS (
    SELECT TOP 1 ps.work_id, w.artist_id, w.[name], ps.regular_price
    FROM dbo.product_size$ ps
	JOIN work$ w ON ps.work_id = w.work_id
    ORDER BY regular_price DESC
),
least_expensive AS (
    SELECT TOP 1 ps.work_id, w.artist_id, w.[name], ps.regular_price
    FROM dbo.product_size$ ps
	INNER JOIN work$ w
	ON ps.work_id = w.work_id
    ORDER BY ps.regular_price ASC
)
SELECT *
FROM most_expensive
UNION ALL
SELECT *
FROM least_expensive;


